databases:
  - name: arogyaai-db
    databaseName: arogyaai
    user: arogyaai_user
    region: singapore
    plan: free

services:
  - type: web
    name: arogyaai
    env: python
    region: singapore
    plan: free
    buildCommand: >
      apt-get install -y tesseract-ocr poppler-utils &&
      pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arogyaai-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"
      - key: OAUTHLIB_RELAX_TOKEN_SCOPE
        value: "1"
    autoDeploy: true