services:
  - type: web
    name: arogyaai
    env: python
    region: singapore
    plan: free
    buildCommand: apt-get install -y tesseract-ocr poppler-utils && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 120
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: OAUTHLIB_INSECURE_TRANSPORT
        sync: false
      - key: OAUTHLIB_RELAX_TOKEN_SCOPE
        sync: false
    autoDeploy: true